site_name: Switch Wiki
site_url: https://wiki.icephoenix.ru
repo_url: https://github.com/Ultra-NX/UltraNX
repo_name: Ultra-NX
nav:
  - Ultra Wiki: index.md
  - Полезные гайды: useful_guides/index.md
theme:
  name: material
  language: ru
  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme)"
    - media: "(prefers-color-scheme: light)"
      scheme: default
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - toc.follow
    - navigation.top
    - navigation.path
    - content.code.copy
plugins:
  - optimize
  - offline
  - social
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - markdown.extensions.toc:
      slugify: !!python/name:slugify.slugify
      permalink: true
  - toc:
      permalink: true
      toc_depth: 3